services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /usr/local/bin/entrypoint.sh
    command: php-fpm -F
    container_name: kondomanager_dev_app
    working_dir: /var/www
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: kondomanager_dev
      DB_USERNAME: kondomanager
      DB_PASSWORD: kondomanager
      AUTO_KEYGEN: "true"
      AUTO_MIGRATE: "true"
      AUTO_SEED: "true"
    env_file:
      - ../.env
    volumes:
      - ..:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: kondomanager_dev_nginx
    ports:
      - "8889:80"
    volumes:
      - ..:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: kondomanager_dev_db
    environment:
      MYSQL_DATABASE: kondomanager_dev
      MYSQL_USER: kondomanager
      MYSQL_PASSWORD: kondomanager
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: kondomanager_dev_phpmyadmin

    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: kondomanager
      PMA_PASSWORD: kondomanager
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8990:80"

    depends_on:
      - db

  # node:
  #   image: node:20
  #   container_name: kondomanager_dev_node
  #   working_dir: /var/www
  #   volumes:
  #     - ..:/var/www
  #   command: npm run dev
  #   ports:
  #     - "5173:5173"


volumes:
  dbdata: